### PR TITLE
Atom/RSS Feeds for popular, latest, category, topic and user

### LINKED ISSUE #188: RSS feed, also for categories
It would be nice to have RSS/Atom feed for the website, say, for the latest, the best, etc. and also for categories. and (maybe in the future) for the users.

### PR DESCRIPTION
**Pull request by mjalajel**
fixes #188. routes:
/feed/popular.(rss|atom)
/feed/latest.(rss|atom)
/feed/category/:id.(rss|atom)
/feed/topic/:id.(rss|atom)
/feed/user/:id.(rss|atom)

### CODE REVIEW

**Comment by mkhatib** [comment]
@mjalajel have you tested this locally? I am not familiar with the atom builder and the file extension you're using, is this using a specific gem?

**Comment by mjalajel** [comment]
I did test it locally and it seemed to work fine. I still need to add some fancy stuff (better titles and such), but this should be a good MVP for this feature.

This uses existing features in rails, no need for gems or anything.

The atom builder is documented here: http://edgeapi.rubyonrails.org/classes/ActionView/Helpers/AtomFeedHelper.html#method-i-atom_feed

**Comment by mkhatib** [comment]
@mjalajel thanks so much for the PR and sorry for the delay! @ahmgeek thanks for the review! 

This looks great! Merging! @mjalajel this has been a big feature request for awhile! 

We need to think of how to allow browsers and users discover the different feeds so they can add them.

**Comment by mkhatib** [comment]
I just realized why it took me so much to notice this pull request :cry:. There were another PR to add RSS feeds and it wasn't very clear and I actually followed up with that one, I guess my brain thought this was the same one. Apologies.

**Pull request merged**
