### PR TITLE
Hide details card in article loading

### PR DESCRIPTION
**Pull request by AhmedGaber**
Hide details card, recommendation and sharing buttons in article loading.

### CODE REVIEW

**Comment by RashaHussein** [comment]
Can you take a screenshot? I kinda have no idea what you're talking about

**Comment by AhmedGaber** [comment]
@RashaHussein 
screenshot from 2015-03-07 01 41 16

**Comment by RashaHussein** [comment]
Oh yeah! Thanks for reminding me about this! I hate it :D

**Comment by AhmedGaber** [comment]
Should I close this PR? Will you fix it?

**Comment by RashaHussein** [comment]
If you fixed it then there's no need for me to do it, no?

**Comment by ahmedissa** [comment]
@RashaHussein  you could use resolve option on $routeProvider to wait until the content load.

**Comment by AhmedGaber** [comment]
I think that I solved the problem, however, the scrollbar and the header may still appear. It would be great If you can get rid of them all while article loading and only show the simple white page. :sunglasses:

**Comment by mkhatib** [comment]
Although Resolving a promise would be the typical way to do it. Not sure if we should try and do a loading effect on the article page similar to what we do when loading the listings of the cards, where a placeholder would pulse to show that the article is still loading. Hiding the recommend and other boxes are fine.

**Comment by RashaHussein** [comment]
We can do the loading udacity style! They flash some sentences before they
load the lesson. It's pretty slow when you first load the course, but I
still read what they say, I wish they change the sentences though :\

**Comment by AhmedGaber** [comment]
OK, I'll just close this PR. Take your time to fix it, Mrs. Awesomeness :blush:

**Comment by mkhatib** [comment]
This addressed one of #172 issues

**Pull request merged**
