### PR TITLE
Adding test coverage to backend

### PR DESCRIPTION
**Pull request by mkhatib**
Using simplecov for coverage reports on the backend. 

The reports are generated in coverage/ folder. So just open the index.html file in there and you can read the coverage.

### CODE REVIEW

**Comment by HammamSamara** [comment]
:+1:

**Comment by amrnt** [comment]
@HammamSamara ... a year later :smile:

**Comment by HammamSamara** [comment]
lol I got some time to play with manshar last night

**Comment by mkhatib** [comment]
Closing this now, will open a bug to track this.

**Pull request closed without merging**
