### PR TITLE
User social media profiles

### PR DESCRIPTION
**Pull request by AhmedGaber**
Added additional 3 columns to the users table:
- facebook_account: type: string, for storing user's Facebook account
- twitter_account: type: string, for for storing user's Twitter account
- is_verified: type: boolean, true for verified accounts, and false otherwise

Also Added some code in the frontend, but commented it as I didn't like the view. So, everything is working, just need some frontend work to show it to the users.

### CODE REVIEW

**Comment by mkhatib** [comment]
I think a better way to address this is by creating a new model for Links in general and then add a relation to the User model (User has_many :links). This will allow the user to add as many links to their profile as they'd like. 

And the client side can determine if this is a special link (social accounts, and display an icon or something). 

What do you guys think?

**Comment by AhmedGaber** [comment]
Hmmm! You may have a point (closest to G+ profiles I presume), but I think that we shouldn't show many links in user profiles, only the famous ones, it's not a CV after all.

I was thinking of adding additional two columns for user website and G+ profile, but I thought it wouldn't be a big deal as the majority of users don't have websites and the popular social websites in the Arab world are Facebook and Twitter. I only wanted to add the links I'm sure that users have.

If you think that treating the links as a separate model would be better, I can change the code.

**Comment by mkhatib** [comment]
I think that would be a better generic solution, otherwise we'll start
receive more request to add more links and so on. People want to add their
blog, or their arabia.io profile or other stuff. Mind trying to implement
it in a separate model? Happy to discuss this further.

**Comment by AhmedGaber** [comment]
Will implement it as you suggested, and will get back to you if I have any question.

**Comment by mkhatib** [comment]
Cool. I think we need a title and a url for the model and user_id. Anything
else?

**Comment by ahmgeek** [comment]
is this for share ? or just to show it on the user profile ? :smile: , am not in the same paper with you guys. 
IMHO: for user profile, we need to show some social accounts, the minimum actually, most sites are biased on this, producthunt, gittip (gratipay now) used to add twitter exclusively ?, so of course we need a couple of them, not to mention the ability to log in socially of course. 
for the implementing, any thing could work. but the neater way is always the best.
the generic one will work amazing for link aggregation : "Read it later"
so idk if it will be good there. but if we will have a separate models for aggregating and social accounts, that would be cool, amd always down for generics, that cause it to be easy on the extending and future expansions :dancer:

**Comment by AhmedGaber** [comment]
"the minimum actually", I like this statement. The implementation is not our problem here, the UX is.

**Comment by ahmgeek** [comment]
they are related in way or another. :icecream:

**Comment by AhmedGaber** [comment]
I will do it in @mkhatib's way. And no, Mk, I don't think we need anything else.

**Pull request closed without merging**
